services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - sqlite-data:/app/apps/backend/prisma

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  sqlite-data: